### PR TITLE
README improvements

### PR DESCRIPTION
**Pull request by mscheel**
1. Fix casing of HAT (not hat) in three README files

### CODE REVIEW

**Comment by mscheel** [comment]
I signed it!

**Comment by devunwired** [comment]
This repository has three README files, which all contain this text. The update should include all of them.

Also, calling out the I/O on the Rainbow HAT is a good idea but we should do so visually with an image of the HAT (the same way we call out the other schematic). We can add this separately, so I'd remove that line from this OR.

**Review by devunwired — CHANGES_REQUESTED** [review]
This repository has three README files, which all contain this text. The update should include all of them.

Also, calling out the I/O on the Rainbow HAT is a good idea but we should do so visually with an image of the HAT (the same way we call out the other schematic). We can add this separately, so I'd remove that line from this PR.

**Comment by mscheel** [comment]
Requested changes have been addressed, thanks Dave for the thoughtful review

**Review by devunwired — APPROVED** [review]

**Pull request merged**
