### PR TITLE
Fix demo image link

### PR DESCRIPTION
**Pull request by benwicks**

### CODE REVIEW

**Comment by Fleker** [comment]
It looks like the gif is copied in the root directory and the `java` directory. We should probably make the same change in the Java README and remove that extra gif.

**Review by Fleker — APPROVED** [review]
Thanks!

**Comment by Fleker** [comment]
Can you also do this with the rpi schematic files?

**Comment by benwicks** [comment]
Yep, I'll take a look!

**Review by Fleker — APPROVED** [review]

**Comment by callingshotgun** [comment]
Close, but in the wrong direction :D The reason for the redundant images is that the indexer that powers Android Studio's "Sample Indexer" treats the separate samples (in this case, the /java and /kotlin subdirectories) as self-contained top-level folders, with no siblings and no parents.  As such, this PR would break schematics being displayed when viewing the java sample README from within Android Studio.

Required steps:
* Move all images displayed in the README to project-root/java (the root for the java sample).
* Copy those images to project-root/kotlin (the root for the kotlin sample)
* To skip pointless redundancy, update project-root/README.md to point to the images in the java subdir instead of creating a third copy of each image.  This allows the README to be displayed properly when visitors browse the sample's landing page on github.
*  Update java/README.md and kotlin/README.md to point to their own local copies of the images, not the images in github project root.

Once those are done I can approve.

**Pull request merged**
