### PR TITLE
Remove duplicate logic

### PR DESCRIPTION
**Pull request by benwicks**

### CODE REVIEW

**Comment by benwicks** [comment]
I signed it!

**Comment by benwicks** [comment]
@devunwired Should I close this?

**Comment by benwicks** [comment]
Will close since my commit had an old e-mail address.

**Review by mangini — COMMENTED** [review]
Thanks for the contribution. Can you remove the second statement (the one outside the finally), just to keep consistency with the mButtonInputDriver block?

**Comment by mangini** [comment]
Oh, I commented before seeing your last comment. Feel free to reopen or resubmit considering my review comment.

**Pull request closed without merging**
